# Generated by Django 3.2 on 2021-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='匿名用户', help_text='只允许8位字符', max_length=8, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='poster',
            field=models.ImageField(default='', help_text='一个图片路径', upload_to='', verbose_name='用户的头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=True, help_text='1为男，0为女', verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign',
            field=models.CharField(default='', help_text='字符串', max_length=32, verbose_name='用户简短的签名'),
        ),
    ]
