# Generated by Django 3.2 on 2021-05-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_user_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poster',
            field=models.ImageField(default='', help_text='一个图片路径', upload_to='lsrc', verbose_name='用户的头像'),
        ),
    ]
