# Generated by Django 3.2 on 2021-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_user_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='如java，python', max_length=32, verbose_name='标签内容')),
            ],
        ),
        migrations.CreateModel(
            name='LabelOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(verbose_name='所属的模块id')),
                ('pid', models.IntegerField(verbose_name='所属内容id')),
                ('uid', models.IntegerField(verbose_name='标签所属用户id')),
                ('did', models.IntegerField(verbose_name='关联的标签id')),
            ],
        ),
    ]
