# Generated by Django 3.2 on 2021-05-02 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_label_labelof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='所属用户id')),
                ('this_id', models.IntegerField(verbose_name='学习计划id')),
                ('parent', models.IntegerField(help_text='父节点为0为根节点', verbose_name='父节点')),
                ('order', models.IntegerField(verbose_name='该父节点下的第几位')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('detail', models.CharField(default='', max_length=32, verbose_name='备注')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间')),
                ('mod_date', models.DateTimeField(auto_now=True, help_text='用来回溯', verbose_name='每次更新时间')),
            ],
        ),
    ]
