# Generated by Django 3.2 on 2021-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='所属用户id')),
                ('title', models.CharField(max_length=32, verbose_name='导航的备注或者描述')),
                ('src', models.TextField(verbose_name='链接')),
            ],
        ),
    ]
