# Generated by Django 3.2 on 2021-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_myapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='相册标题')),
                ('detail', models.CharField(max_length=32, verbose_name='相册备注')),
                ('poster', models.ImageField(upload_to='', verbose_name='相册封面')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='照片标题')),
                ('src', models.ImageField(upload_to='', verbose_name='照片地址')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(verbose_name='相册id')),
                ('pid', models.IntegerField(verbose_name='图片id')),
            ],
        ),
    ]
