# Generated by Django 3.2 on 2021-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_album_photo_photoof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='所属用户')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('poster', models.ImageField(default='', upload_to='', verbose_name='封面')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
            ],
        ),
    ]
