# Generated by Django 3.2 on 2021-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='file', verbose_name='文件'),
        ),
    ]
